### PR TITLE
New Relic dotnet framework agent support

### PR DESCRIPTION
**Pull request by shahramk**
Hi,

I am creating a PR for New Relic dotnet framework agent support to this repo. Here are some details:
* modified the src/hwc/compile/compile.go to invoke InstallNewRelic()
* added src/hwc/compile/newrelic.go to determine if required, and handle new relic agent installation
* added new relic agent dependency to **manifest.yml** for cached buildpack
* added **newrelic.config** and **Procfile** to the buildpack
* added **docs/newrelic.md** with instructions on how to use new relic

thank you

### CODE REVIEW

**Comment by astrieanna** [comment]
@shahramk Thanks for this PR.

I don't see any tests for this new behavior. Could you add a fixture for an app that uses NewRelic and an integration test that exercises it?

**Comment by astrieanna** [comment]
@shahramk It looks like a fair amount of `newrelic.go` is downloading and checking a file. The `libbuildpack` library is designed to handle this for dependencies listed in the `manifest.yml` of the buildpack.

For an example of how to do this -- in this buildpack, the only dependency is `hwc`. You can see it listed in `manifest.yml` and you can see it installed in `compile.go`: https://github.com/cloudfoundry/hwc-buildpack/blob/master/src/hwc/compile/compile.go#L74

Does that make sense? The libbuildpack code can download the file, check the sha, and extract the zip file for you. Putting the dependency in the manifest will also allow the offline/cached buildpack to include the dependency.

**Comment by micahyoung** [comment]
Hey @shahramk . I know we had worked together a few months back on an extension buildpack to cover this same feature set. How is that progressing? Are we able to close out this PR in favor of your extension buildpack or are there still needed features here in HWC buildpack?

**Comment by shahramk** [comment]
hello @micahyoung - since we developed extensions for both dotnet core and framework, this PR is not needed anymore.  Thank you

**Pull request closed without merging**
